name: Auto Work on Issue

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request_testing:
    runs-on: ubuntu-latest

    steps:
      # test ci/ cd
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v2

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"

      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
    
     # Check if the pull request has a description
      - name: Check PR Description
        run: |
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r '.body')
          
          if [ -z "$PR_DESCRIPTION" ]; then
            echo "Error: Pull request must have a description."
            exit 1
          fi

      # install dependencies
      - name: Install dependencies
        run: yarn install

      # build the react app
      - name: Build
        run: yarn run build
